#!/bin/bash

source ./scripts/bash/log.sh

set -eu

function download_platform_automation_toolkit {

  logGreen "Start: Download Platform Automation Toolkit"

    download_pivnet_file ${PLATFORM_AUTOMATION_PRODUCT_SLUG} "${PLATFORM_AUTOMATION_VERSION}" $PLATFORM_AUTOMATION_FILE1_ID ${DOWNLOAD_DIR} $PLATFORM_AUTOMATION_FILE1_NAME
    download_pivnet_file ${PLATFORM_AUTOMATION_PRODUCT_SLUG} "${PLATFORM_AUTOMATION_VERSION}" $PLATFORM_AUTOMATION_FILE2_ID ${DOWNLOAD_DIR} $PLATFORM_AUTOMATION_FILE2_NAME

  logGreen "End: Download Platform Automation Toolkit"

}

function download_concourse_for_platform_automation {

  logGreen "Start: Download Concourse for Platform Automation Toolkit"

    download_pivnet_file ${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_PRODUCT_SLUG} "${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_VERSION}" $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE1_ID ${DOWNLOAD_DIR} $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE1_NAME
    download_pivnet_file ${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_PRODUCT_SLUG} "${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_VERSION}" $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE2_ID ${DOWNLOAD_DIR} $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE2_NAME
    download_pivnet_file ${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_PRODUCT_SLUG} "${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_VERSION}" $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE3_ID ${DOWNLOAD_DIR} $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE3_NAME
    download_pivnet_file ${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_PRODUCT_SLUG} "${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_VERSION}" $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE4_ID ${DOWNLOAD_DIR} $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE4_NAME
    download_pivnet_file ${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_PRODUCT_SLUG} "${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_VERSION}" $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE5_ID ${DOWNLOAD_DIR} $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE5_NAME
    download_pivnet_file ${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_PRODUCT_SLUG} "${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_VERSION}" $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE6_ID ${DOWNLOAD_DIR} $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE6_NAME
    download_pivnet_file ${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_PRODUCT_SLUG} "${CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_VERSION}" $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE7_ID ${DOWNLOAD_DIR} $CONCOURSE_FOR_VMWARE_TANZU_PLATFORM_AUTOMATION_FILE7_NAME

  logGreen "End: Download Concourse for Platform Automation Toolkit"

}

function download_opsman {

  logGreen "Start: Download OpsMan"

    case $IAAS in
      "azure" )

        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_AZURE_FILE1_ID ${DOWNLOAD_DIR} $OPS_MANAGER_AZURE_FILE1_NAME
        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_AZURE_FILE2_ID ${DOWNLOAD_DIR} $OPS_MANAGER_AZURE_FILE2_NAME

        ;;
      "aws" )

        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_AWS_FILE1_ID ${DOWNLOAD_DIR} $OPS_MANAGER_AWS_FILE1_NAME
        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_AWS_FILE2_ID ${DOWNLOAD_DIR} $OPS_MANAGER_AWS_FILE2_NAME

        ;;
      "gcp" )

        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_GCP_FILE1_ID ${DOWNLOAD_DIR} $OPS_MANAGER_GCP_FILE1_NAME
        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_GCP_FILE2_ID ${DOWNLOAD_DIR} $OPS_MANAGER_GCP_FILE2_NAME

        ;;
      "openstack" )

        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_OPENSTACK_FILE1_ID ${DOWNLOAD_DIR} $OPS_MANAGER_OPENSTACK_FILE1_NAME

        ;;
      "vsphere" )

        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" $OPS_MANAGER_VSPHERE_FILE1_ID ${DOWNLOAD_DIR} $OPS_MANAGER_VSPHERE_FILE1_NAME

        ;;
      *)

        logGreen "Reached default ;)"

        ;;
    esac

    if [ $DOWNLOAD_BOSH_ASSETS == "true" ]
    then
        download_pivnet_file ${OPS_MANAGER_VERSION_PRODUCT_SLUG} "${OPS_MANAGER_VERSION}" 633043 ${DOWNLOAD_DIR} "BOSH Assets - 2.9.0-build.106"
    fi

  logGreen "End: Download OpsMan"

}

function download_stemcells {

  logGreen "Start: Download Stemcells"

    case $IAAS in
      "azure" )
        download_pivnet_file ${UBUNTU_XENIAL_STEMCELL_PRODUCT_SLUG} "${UBUNTU_XENIAL_STEMCELL_VERSION}" 667981 ${DOWNLOAD_DIR} "Ubuntu Xenial Stemcell for Azure 456.104"
        ;;
      "aws" )
        download_pivnet_file ${UBUNTU_XENIAL_STEMCELL_PRODUCT_SLUG} "${UBUNTU_XENIAL_STEMCELL_VERSION}" 667978 ${DOWNLOAD_DIR} "Ubuntu Xenial Stemcell for AWS 456.104"
        ;;
      "gcp" )
        download_pivnet_file ${UBUNTU_XENIAL_STEMCELL_PRODUCT_SLUG} "${UBUNTU_XENIAL_STEMCELL_VERSION}" 667987 ${DOWNLOAD_DIR} "Ubuntu Xenial Stemcell for GCP 456.104"
        ;;
      "openstack" )
        download_pivnet_file ${UBUNTU_XENIAL_STEMCELL_PRODUCT_SLUG} "${UBUNTU_XENIAL_STEMCELL_VERSION}" 667990 ${DOWNLOAD_DIR} "Ubuntu Xenial Stemcell for OpenStack 456.104"
        ;;
      "vsphere" )
        download_pivnet_file ${UBUNTU_XENIAL_STEMCELL_PRODUCT_SLUG} "${UBUNTU_XENIAL_STEMCELL_VERSION}" 668003 ${DOWNLOAD_DIR} "Ubuntu Xenial Stemcell for OpenStack 456.104"
        ;;
      "vcloud" )
        download_pivnet_file ${UBUNTU_XENIAL_STEMCELL_PRODUCT_SLUG} "${UBUNTU_XENIAL_STEMCELL_VERSION}" 667996 ${DOWNLOAD_DIR} "Ubuntu Xenial Stemcell for OpenStack 456.104"
        ;;
      *)

        logGreen "Reached default ;)"

        ;;
    esac

    if [ $AWS_HEAVY_STEMCELL == "true" ]
    then
        download_pivnet_file ${UBUNTU_XENIAL_STEMCELL_PRODUCT_SLUG} "${UBUNTU_XENIAL_STEMCELL_VERSION}" 667976 ${DOWNLOAD_DIR} "Ubuntu Xenial Stemcell for AWS (Heavy) 456.104"
    fi

  logGreen "End: Download Stemcells"

}

function download_products {

  logGreen "Start: Download Products"
    # download_platform_automation_toolkit
    # download_concourse_for_platform_automation
    # download_opsman
    download_stemcells
  logGreen "End: Download Products"

}